language: android
android:
  components:
    - tools
    - platform-tools

    - build-tools-27.0.0

    - android-26

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-22
